-- Shared exercise library (user_id null). Safe to re-run.
insert into exercises (user_id, name, muscle_group, is_custom) values
  (null, 'Barbell Bench Press',        'chest',     false),
  (null, 'Incline Barbell Bench Press','chest',     false),
  (null, 'Dumbbell Bench Press',       'chest',     false),
  (null, 'Incline Dumbbell Press',     'chest',     false),
  (null, 'Machine Chest Press',        'chest',     false),
  (null, 'Pec Deck / Chest Fly',       'chest',     false),
  (null, 'Cable Crossover',            'chest',     false),
  (null, 'Push-Up',                    'chest',     false),
  (null, 'Barbell Back Squat',         'quads',     false),
  (null, 'Front Squat',                'quads',     false),
  (null, 'Leg Press',                  'quads',     false),
  (null, 'Hack Squat',                 'quads',     false),
  (null, 'Leg Extension',              'quads',     false),
  (null, 'Walking Lunge',              'quads',     false),
  (null, 'Romanian Deadlift',          'hamstrings',false),
  (null, 'Lying Leg Curl',             'hamstrings',false),
  (null, 'Seated Leg Curl',            'hamstrings',false),
  (null, 'Conventional Deadlift',      'hamstrings',false),
  (null, 'Hip Thrust',                 'glutes',    false),
  (null, 'Glute Kickback',             'glutes',    false),
  (null, 'Standing Calf Raise',        'calves',    false),
  (null, 'Seated Calf Raise',          'calves',    false),
  (null, 'Pull-Up',                    'back',      false),
  (null, 'Lat Pulldown',               'back',      false),
  (null, 'Seated Cable Row',           'back',      false),
  (null, 'Bent-Over Barbell Row',      'back',      false),
  (null, 'Single-Arm Dumbbell Row',    'back',      false),
  (null, 'Chest-Supported Row',        'back',      false),
  (null, 'Face Pull',                  'back',      false),
  (null, 'Overhead Press',             'shoulders', false),
  (null, 'Seated Dumbbell Shoulder Press','shoulders',false),
  (null, 'Machine Shoulder Press',     'shoulders', false),
  (null, 'Lateral Raise',              'shoulders', false),
  (null, 'Rear Delt Fly',              'shoulders', false),
  (null, 'Barbell Curl',               'biceps',    false),
  (null, 'Dumbbell Curl',              'biceps',    false),
  (null, 'Hammer Curl',                'biceps',    false),
  (null, 'Cable Curl',                 'biceps',    false),
  (null, 'Preacher Curl',              'biceps',    false),
  (null, 'Triceps Pushdown',           'triceps',   false),
  (null, 'Overhead Triceps Extension', 'triceps',   false),
  (null, 'Close-Grip Bench Press',     'triceps',   false),
  (null, 'Skull Crusher',              'triceps',   false),
  (null, 'Dip',                        'triceps',   false),
  (null, 'Plank',                      'core',      false),
  (null, 'Hanging Leg Raise',          'core',      false),
  (null, 'Cable Crunch',               'core',      false),
  (null, 'Ab Wheel Rollout',           'core',      false)
on conflict do nothing;
