#!/usr/bin/env node
/**
 * Bundles every migration, plus the seed, into a few files you can paste into
 * the Supabase SQL editor to set up a fresh project (the dev project).
 *
 *   npm run db:bundle
 *
 * Writes supabase/dev-setup/part-1.sql, part-2.sql, ... Run them in order,
 * each on its own. They are split because the SQL editor runs a script as one
 * transaction, and Postgres will not use a new enum value in the transaction
 * that added it, so a part ends after any migration that adds one.
 *
 * The seed goes in right after migration 0002, which is where it ran in
 * production. `npm run test:db` applies these same parts, each in a single
 * transaction, to prove they work.
 */

const fs = require('fs');
const path = require('path');

const SUPABASE = path.join(__dirname, '..', 'supabase');
const MIGRATIONS = path.join(SUPABASE, 'migrations');
const OUT = path.join(SUPABASE, 'dev-setup');
const SEED_AFTER = 2;
const ADDS_ENUM_VALUE = /alter\s+type\s+\S+\s+add\s+value/i;

/** Returns the parts as arrays of { name, sql }. */
function buildParts() {
  const files = fs
    .readdirSync(MIGRATIONS)
    .filter((f) => /^\d{4}_.*\.sql$/.test(f))
    .sort();
  const parts = [[]];
  for (const name of files) {
    const sql = fs.readFileSync(path.join(MIGRATIONS, name), 'utf8');
    parts[parts.length - 1].push({ name, sql });
    if (Number(name.slice(0, 4)) === SEED_AFTER) {
      parts[parts.length - 1].push({ name: 'seed.sql', sql: fs.readFileSync(path.join(SUPABASE, 'seed.sql'), 'utf8') });
    }
    if (ADDS_ENUM_VALUE.test(sql)) parts.push([]);
  }
  return parts.filter((p) => p.length > 0);
}

function render(part, index, total) {
  const header =
    `-- Rust Strength: fresh project setup, part ${index + 1} of ${total}.\n` +
    '-- Generated by scripts/build-dev-sql.js. Do not edit; edit the migrations.\n' +
    `-- Paste into the Supabase SQL editor and run${index + 1 < total ? `, then run part ${index + 2}` : ''}.\n` +
    `-- Contains: ${part.map((f) => f.name).join(', ')}\n`;
  return header + part.map((f) => `\n-- ===== ${f.name} =====\n${f.sql}\n`).join('');
}

if (require.main === module) {
  const parts = buildParts();
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });
  parts.forEach((part, i) => {
    fs.writeFileSync(path.join(OUT, `part-${i + 1}.sql`), render(part, i, parts.length));
  });
  console.log(`Wrote ${parts.length} parts to ${path.relative(process.cwd(), OUT)}:`);
  parts.forEach((part, i) => console.log(`  part-${i + 1}.sql  ${part.map((f) => f.name).join(', ')}`));
}

module.exports = { buildParts, render };
